backend:
  name: git-gateway
  branch: master
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "public/assets" # Media files will be stored in the repo under public/assets
public_folder: "/assets"
i18n:
  structure: multiple_files
  locales: [en, es]
  default_locale: en
collections:
  - name: "level"
    label: "Level"
    folder: "content/levels"
    nested:
      depth: 5
    create: true
    i18n: true
    fields:
      - { label: "name", name: "name", widget: "string", i18n: true }
      - { label: "displayName", name: "displayName", widget: "string", i18n: true}
      - { label: "tooltip", name: "tooltip", widget: text, i18n: true }
  - name: "attribute"
    label: "Attribute"
    folder: "content/attributes"
    create: true
    i18n: true
    fields: 
      - { label: "name", name: "name", widget: "string", i18n: true }
      - { label: "displayName", name: "displayName", widget: "string", i18n: true}
      - { label: "tooltip", name: "tooltip", widget: text, i18n: true }
      - label: "Levels"
        name: "levels"
        widget: "list"
        i18n: true
        fields: 
          - label: "Level"
            name: "level"
            widget: "relation"
            collection: "level"
            search_fields: ["name", "displayName"]
            value_field: "name"
            display_fields: ["displayName"]
            i18n: true
  - name: "part1"
    label: "Part 1"
    folder: "content/part1"
    create: true
    i18n: true
    fields:
      - { label: "title", name: "title", widget: "string", i18n: true }
      - { label: "body", name: "body", widget: "markdown", i18n: true }
      - label: "Attributes"
        name: "attrs"
        widget: "list"
        i18n: true
        fields:
          - label: "Attribute"
            name: "Attribute"
            widget: "relation"
            collection: "attribute"
            search_fields: ["name", "displayName"]
            value_field: "name"
            display_fields: ["displayName"]
            i18n: true