backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "public/assets" # Media files will be stored in the repo under public/assets
public_folder: "/assets"
collections:
  - name: "part1"
    label: "Part 1"
    folder: "content/part1"
    create: true
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "body", name: "body", widget: "markdown" }
      - label: "attrs"
        name: "attrs"
        widget: list
        fields:
          - { label: "name", name: "name", widget: "string" }
          - { label: "tooltip", name: "tooltip", widget: "text"}